// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://qpzutdlkeegwiqkphqkj.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Verificar se as variáveis estão definidas
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn('⚠️ Variáveis do Supabase não configuradas. Configure VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY.');
  console.warn('URL:', SUPABASE_URL);
  console.warn('Key configurada:', !!SUPABASE_PUBLISHABLE_KEY);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

// Testar conexão ao inicializar
if (typeof window !== 'undefined') {
  (async () => {
    try {
      const { error } = await supabase.from('transactions').select('count').limit(1);
      if (error) {
        console.error('❌ Erro ao conectar com Supabase:', error);
        console.error('URL:', SUPABASE_URL);
        console.error('Key:', SUPABASE_PUBLISHABLE_KEY ? 'Configurada' : 'Não configurada');
      } else {
        console.log('✅ Conexão com Supabase estabelecida');
      }
    } catch (err) {
      console.error('❌ Erro ao testar conexão Supabase:', err);
    }
  })();
}